### PR TITLE
APPS-338 Run workflow | EvalException: identifier not found

### PR DESCRIPTION
**Pull request by r-i-v-a**
Fixes APPS-338

### CODE REVIEW

**Comment by jdidion** [comment]
I added a unit test to wdlTools for evaluating select_first with a None value and it passes, so I'm almost certain the bug is in dxCompiler. I believe when it evaluates the expression it is not including inputs with unset values in the env. Will investigate on Monday.

**Review by commandlinegirl — APPROVED** [review]
LGTM, thanks for the fixes!

**Comment by jdidion** [comment]
Updating to the latest wdlTools seems to fix the issue.

**Comment by commandlinegirl** [comment]
@jdidion Which tickets/issues your commits fix?

**Comment by r-i-v-a** [comment]
> @jdidion Which tickets/issues your commits fix?

https://jira.internal.dnanexus.com/browse/APPS-338 @commandlinegirl 

I'm going to rename this PR since @jdidion is working on APPS-338 here. Feel free to merge if it fixes the issue; I can make a new branch to continue APPS-320.

**Review by commandlinegirl — APPROVED** [review]

**Review by commandlinegirl — APPROVED** [review]

**Pull request merged**
