### PR TITLE
APPS-1694 Snyk | Pin cryptography version in requirements.txt to avoid vulnerability

### PR DESCRIPTION
**Pull request by r-i-v-a**
The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-3112177
- https://snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-3112180

The original PR was generated by Snyk bot, but had issues

1. Problems installing the package while running GHA, can probably be resolved by upgrading pip and/or setuptools in GHA, working on it
2. It was 300+ commits behind develop; I suspect this is due to Snyk using 'master' when it should use 'develop' branch -- APPS-1695

### CODE REVIEW

**Comment by r-i-v-a** [comment]
[X] Applied commit from Snyk's originl PR

**Comment by r-i-v-a** [comment]
[] Resolving issues where GHA runs fail due to installation problems

**Comment by r-i-v-a** [comment]
[X] Scala unit tests ok https://github.com/dnanexus/dxCompiler/actions/runs/4325424228/jobs/7551568130
[X] dxcint tests ok https://github.com/dnanexus/dxCompiler/actions/runs/4325424239/jobs/7551568275
[X] Linters ok https://github.com/dnanexus/dxCompiler/actions/runs/4325424238/jobs/7551568127

**Comment by r-i-v-a** [comment]
CWL conformance, no problems during installation / so far https://github.com/dnanexus/dxCompiler/actions/runs/4325424240/jobs/7551568184
Integration tests, no problems during installation / so far https://github.com/dnanexus/dxCompiler/actions/runs/4325424245/jobs/7551568133

**Comment by r-i-v-a** [comment]
[X] Nothing fails due to pip installation issues

**Comment by r-i-v-a** [comment]
[] Integration tests are failing later, but the workflows ran -- I think some maintenance was happening on staging during the describe analysis & compare outputs phase. I'll try re-running it in a bit.

**Review by Gvaihir — APPROVED** [review]

**Comment by Gvaihir** [comment]
All checks passed, removed labels and added minor to streamline the merge prior to 2.10.9 release

**Pull request merged**
