### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by jdidion**
Unit tests are failing and integration tests are hanging - may be due to tests from multiple PRs trying to run at the same time. This branch merges two approved PRs in an attempt to get tests to pass.

### CODE REVIEW

**Review by commandlinegirl — APPROVED** [review]
Thanks, I created a ticket for the conflicting unit test runs and we'll deal with it.

**Comment by jdidion** [comment]
@commandlinegirl integration tests still appear to be hanging

**Comment by commandlinegirl** [comment]
> @commandlinegirl integration tests still appear to be hanging

It seems a lot of jobs a still in the idle state https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor and some are still running. It's a limitation of GHA that it doesn't show the test log as it's generated (or takes a long time to load it).

**Comment by jdidion** [comment]
ah - I wonder if this is related to the AWS outage

**Pull request merged**
