### PR TITLE
create scatter job names using file names

### PR DESCRIPTION
**Pull request by jdidion**
Use the file name when creating names for scatter jobs.
This requires:
* dxApi 0.1.4, which caches the file name on DxFile if there is no describe
* dxFileAccessProtocols 0.1.2, which extracts the fileName from an "extended" dx URI and caches it on the DxFile

### CODE REVIEW

**Comment by commandlinegirl** [comment]
What are `dxApi` and `dxFileAccessProtocols`?

**Review by commandlinegirl — COMMENTED** [review]
Do we have a scatter test where we could add a check for job names?

**Comment by jdidion** [comment]
Added a test

**Review by commandlinegirl — APPROVED** [review]
Thanks!

**Pull request merged**
