### PR TITLE
Null array as empty

### PR DESCRIPTION
**Pull request by jdidion**
DNAnexus does not distinguish between null and empty fo array inputs. Currently, if an empty array is passed to a non-optional WDL array input there is an error, even if the WDL array is allowed to be empty. This change (which depends on a new version of wdlTools) substitutes an empty array for a null value in the case of a non-optional array that is allowed to be empty.

### CODE REVIEW

**Review by commandlinegirl — APPROVED** [review]
LGTM, thanks!

**Review by r-i-v-a — APPROVED** [review]

**Review by r-i-v-a — CHANGES_REQUESTED** [review]
Test failure message 

Error:  /home/runner/work/dxCompiler/dxCompiler/executorWdl/src/main/scala/dx/executor/wdl/WdlWorkflowExecutor.scala:297:84: unknown parameter name: strict
Error:          val callInputs = callIO.inputsFromValues(inputWdlValues, evaluator, strict = true)
Error:                                                                                     ^
Error:  one error found

**Review by commandlinegirl — CHANGES_REQUESTED** [review]
The `inputsFromValues` here also need to be updated: https://github.com/dnanexus/dxCompiler/blob/a173927bb3b1f033eef6501b6c743e64acf57723/executorWdl/src/main/scala/dx/executor/wdl/WdlWorkflowExecutor.scala#L297

**Comment by jdidion** [comment]
@commandlinegirl @r-i-v-a fixed - please re-review

**Review by commandlinegirl — APPROVED** [review]

**Pull request merged**
