### PR TITLE
APPS-1170, APPS-1154 Update  version of cwlScala, dxCommon, wdlTools

### PR DESCRIPTION
**Pull request by commandlinegirl**

### CODE REVIEW

**Comment by commandlinegirl** [comment]
CWL conformance tests passed.

**Comment by commandlinegirl** [comment]
CWL conformance tests - passed
Integration tests (M) - passed
Multi-user integration test - passed when using dxpy==0.323.0
Unit tests - passed

**Review by YuxinShi0423 — APPROVED** [review]
LGTM. Thanks!

**Comment by YuxinShi0423** [comment]
@commandlinegirl Shall we also mention the dependency updates in release notes?

**Review by YuxinShi0423 — COMMENTED** [review]
Shall we also mention the dependency changes in release notes?

**Comment by commandlinegirl** [comment]
> Shall we also mention the dependency changes in release notes?

Yes, thanks for the mention! I'll add them in the release branch.

**Pull request merged**
