### PR TITLE
APPS-1010 Refactor code for compiling, running test workflows --> util.py.

### PR DESCRIPTION
**Pull request by r-i-v-a**
Moving some reusable code to util.py so it can also be used in APPS-627, multi-user test for global WDL workflows.

### CODE REVIEW

**Comment by r-i-v-a** [comment]
Integration tests are failing at `sbt assembly` -- I think this is related to the sbt 1.5.7 update. @jdidion  @commandlinegirl

**Review by commandlinegirl — DISMISSED** [review]
LGTM, thanks!

**Comment by r-i-v-a** [comment]
Rebased on develop branch.

**Review by commandlinegirl — DISMISSED** [review]

**Comment by r-i-v-a** [comment]
Fixed; integration tests are passing now. @commandlinegirl  @jdidion

**Review by commandlinegirl — APPROVED** [review]
LGTM

**Pull request merged**
