### PR TITLE
APPS-1082 Update dev readme dependencies

### PR DESCRIPTION
**Pull request by Gvaihir**
APPS-1082 dev_readme_dependencies
(fix) Developing.md - added few notes on dependencies set up

### CODE REVIEW

**Review by commandlinegirl — APPROVED** [review]
LGTM, thank you! 

BTW: The format for the commit message would be `APPS-1082 Update ....`

**Comment by Gvaihir** [comment]
> BTW: The format for the commit message would be `APPS-1082 Update ....`


Meaning it should've been like that?
```
APPS-1082 dev_readme_dependencies
(fix) Developing.md - added few notes on dependencies set up
```
Meaning every message would start with a title of a PR?
Thanks!

**Comment by commandlinegirl** [comment]
> > BTW: The format for the commit message would be `APPS-1082 Update ....`
> 
> Meaning it should've been like that?
> 
> ```
> APPS-1082 dev_readme_dependencies
> (fix) Developing.md - added few notes on dependencies set up
> ```
> 
> Meaning every message would start with a title of a PR? Thanks!

Yes. You can check the commit history for an example.

**Comment by Gvaihir** [comment]
> > > BTW: The format for the commit message would be `APPS-1082 Update ....`
> > 
> > 
> > Meaning it should've been like that?
> > ```
> > APPS-1082 dev_readme_dependencies
> > (fix) Developing.md - added few notes on dependencies set up
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Meaning every message would start with a title of a PR? Thanks!
> 
> Yes. You can check the commit history for an example.

Sorry, not sure I understand. My PR is exactly of the same structure as [this](https://github.com/dnanexus/dxCompiler/pull/269) for example. My commit messages have the following structure
```
Branch name
(type of change) FileName.extension - description
```
Is this an appropriate structure?
Github formats the first line as the PR title, and the rest goes into commit messages which ideally are different for each commit. Also, last commit message went to the opening comment for the PR.

**Comment by commandlinegirl** [comment]
@Gvaihir Sorry if I was not clear, I mean this title: 
image

It should be:
image

And then the commit message (title) should be something like:
image

**Pull request merged**
