### PR TITLE
APPS-262 Increase disambiguation dir limit to 5000

### PR DESCRIPTION
**Pull request by jdidion**

### CODE REVIEW

**Comment by commandlinegirl** [comment]
Two native_docker_file_image integration tests failed, due to:
```VIEW permission required in project-FGpfqjQ0ffPF1Q106JYP2j3v to perform this action```
Changed the project to dxCompiler_playground and rerunning tests.

**Review by commandlinegirl — APPROVED** [review]
LGTM, thanks!

**Comment by jdidion** [comment]
When I run the unit tests locally they pass. I wonder if there is some issue with the unit tests being run concurrently for multiple PRs?

**Review by commandlinegirl — APPROVED** [review]
Thanks!

**Pull request merged**
