### PR TITLE
APPS-1381 Fix for struct change recompile

### PR DESCRIPTION
**Pull request by Gvaihir**
Depends on https://github.com/dnanexus/wdlTools/pull/233
Struct composition is appended to the "Help" attribute of the inputs for checksum

### CODE REVIEW

**Review by commandlinegirl — COMMENTED** [review]
It looks like the unit tests are failing

**Comment by Gvaihir** [comment]
> It looks like the unit tests are failing

Depends on https://github.com/dnanexus/wdlTools/pull/233
See my OP

**Comment by commandlinegirl** [comment]
> > It looks like the unit tests are failing
> 
> Depends on [dnanexus/wdlTools#233](https://github.com/dnanexus/wdlTools/pull/233) See my OP

My bad, I looked at this PR in the evening and I missed the dependency. I reviewed the pre-requisite.

**Review by commandlinegirl — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
