### PR TITLE
APPS-751 Readme / script for extracting source code from metadata

### PR DESCRIPTION
**Pull request by r-i-v-a**

### CODE REVIEW

**Comment by r-i-v-a** [comment]
Please review @jdidion

**Comment by jdidion** [comment]
Is `base64` available on every platform, or do we have to list that as a prerequisite?

**Comment by r-i-v-a** [comment]
> Is `base64` available on every platform, or do we have to list that as a prerequisite?

I think jq is also a prerequisite that needs to be installed; gunzip, sed, awk should be available I think? 

Do you have a specific place in mind for listing prerequisites, or do you just mean mention it in a comment in the script? @jdidion

**Comment by r-i-v-a** [comment]
> I would mention it both in the script and in the `Internals` documentation.

Done, ready for review @jdidion

**Comment by r-i-v-a** [comment]
Ready for review @jdidion

**Review by jdidion — APPROVED** [review]

**Pull request merged**
