### PR TITLE
APPS-1281 fix cwl types casting between scatters

### PR DESCRIPTION
**Pull request by YuxinShi0423**

### CODE REVIEW

**Comment by YuxinShi0423** [comment]
@Gvaihir @commandlinegirl 
The conformance test 
https://github.com/dnanexus/dxCompiler/runs/7503941731?check_suite_focus=true
failed on the same sets of tests as in another GHA in the PR #359 
https://github.com/dnanexus/dxCompiler/actions/runs/2720614615

So it might not be something code change-related. 

What is confusing is that I got no problem running the test code locally with cwltool. 

I ran one of those failed tests using develop branch, but failed again with the same error:
https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFPJ3980yzZqPqKk56Pkx37z

and failed using v2.10.2 which used the earlier version of cwltool:
https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFPJXkj0yzZp0z1q54zjq0p2

However we have a successful run https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFGPJ0j0yzZVVzKyK46zFXbVz
in from PR #355 on 07/20
https://github.com/dnanexus/dxCompiler/actions/runs/2709591309

**Comment by YuxinShi0423** [comment]
> @Gvaihir @commandlinegirl The conformance test https://github.com/dnanexus/dxCompiler/runs/7503941731?check_suite_focus=true failed on the same sets of tests as in another GHA in the PR #359 https://github.com/dnanexus/dxCompiler/actions/runs/2720614615
> 
> So it might not be something code change-related.
> 
> What is confusing is that I got no problem running the test code locally with cwltool.
> 
> I ran one of those failed tests using develop branch, but failed again with the same error: https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFPJ3980yzZqPqKk56Pkx37z
> 
> and failed using v2.10.2 which used the earlier version of cwltool: https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFPJXkj0yzZp0z1q54zjq0p2
> 
> However we have a successful run https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFGPJ0j0yzZVVzKyK46zFXbVz in from PR #355 on 07/20 https://github.com/dnanexus/dxCompiler/actions/runs/2709591309

Also in PR #357 
https://github.com/dnanexus/dxCompiler/runs/7510050545?check_suite_focus=true

@Gvaihir @commandlinegirl

**Comment by Gvaihir** [comment]
> However we have a successful run https://staging.dnanexus.com/projects/Fy9QqgQ0yzZbg9KXKP4Jz6Yq/monitor/job/GFGPJ0j0yzZVVzKyK46zFXbVz
> in from PR #355 on 07/20

I merged `develop` in that branch, and conformance fails now at those exact tests.
EDIT: that exact test run no longer pass after re-run 07/26

**Comment by Gvaihir** [comment]
Worked:
* Released 2.10.2 from github releases.

Failed:
* Local build of 2.10.2 from source code 


Also: as of 07/26 - same behavior is happening on PROD with 2.10.3-SNAPSHOT

**Comment by Gvaihir** [comment]
Next target to investigate - python dependencies in the executor assets. 
1. Compile with develop and with the released versions. Use a faulty version of workflow to debug both. 
2. ssh to the workers
3. `pip list`. Compare lists.

**Comment by Gvaihir** [comment]
`salad-schema` has to be pinned to `8.2.20220204150214`
Was about to create an issue - but was already created by the devs 11 hrs ago. https://github.com/common-workflow-language/schema_salad/issues/575

**Review by Gvaihir — APPROVED** [review]

**Pull request merged**
